// Cat toy furniture: hand-authored pixel templates (MIT, like the repo).
// One character = one pixel; PALETTE maps characters to RGBA. The cat sprite
// generator reuses BOX_ROWS and PALETTE so a cat peeking out of the box
// matches the box furniture pixel for pixel.

export const PALETTE = {
  '.': [0, 0, 0, 0],
  o: [46, 28, 32, 255], // outline
  W: [204, 156, 102, 255], // wood
  w: [166, 116, 70, 255],
  v: [120, 80, 48, 255],
  S: [232, 208, 158, 255], // sisal rope
  s: [200, 170, 116, 255],
  r: [156, 124, 80, 255],
  C: [96, 166, 176, 255], // carpeted platform
  c: [64, 124, 138, 255],
  L: [150, 206, 210, 255],
  B: [214, 164, 100, 255], // cardboard
  b: [176, 128, 74, 255],
  k: [92, 60, 40, 255],
  t: [236, 214, 168, 255],
  Y: [232, 96, 124, 255], // yarn
  y: [186, 62, 94, 255],
  z: [250, 164, 180, 255],
  F: [232, 82, 72, 255], // feather
  f: [248, 172, 72, 255],
  G: [250, 224, 112, 255],
  P: [196, 196, 206, 255], // metal pole
  p: [136, 136, 152, 255],
  T: [88, 128, 206, 255], // tunnel fabric
  n: [58, 90, 154, 255],
  u: [244, 204, 92, 255],
  q: [30, 28, 48, 255],
  M: [172, 172, 182, 255], // toy mouse
  m: [122, 122, 136, 255],
  e: [242, 162, 172, 255],
  x: [24, 16, 20, 255],
  R: [204, 104, 92, 255], // cat bed
  Q: [156, 72, 66, 255],
  I: [246, 230, 204, 255],
  i: [216, 196, 166, 255],
};

/** Shared with the cat sheet: the box a cat peeks out of (16x16). */
export const BOX_ROWS = [
  '................',
  '................',
  '.oo..........oo.',
  '.otoo......ootbo',
  '.obttoooooottbo.',
  '..oBkkkkkkkkkbo.',
  '..oBkkkkkkkkkbo.',
  '..oBBBBBBBBBBbo.',
  '..oBBBBttBBBBbo.',
  '..oBBBBttBBBBbo.',
  '..oBBBBBBBBBBbo.',
  '..oBBBBBBBBBBbo.',
  '..obBBBBBBBBbbo.',
  '..obbbbbbbbbbbo.',
  '..ooooooooooooo.',
  '................',
];

const YARN = [
  '................',
  '................',
  '................',
  '................',
  '.....oooooo.....',
  '....ozzYYyYo....',
  '...ozYYyYYYyo...',
  '...oYYyYYyYYo...',
  '...oyYYYyYYyo...',
  '...oYyYYYyYYo...',
  '...oYYyYyYYyo...',
  '....oyYYyYyo....',
  '.....oooooooo...',
  '...........oYo..',
  '............oYo.',
  '.............o..',
];

const MOUSE = [
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '.......oo.......',
  '......oeMo......',
  '....ooMMMMo.....',
  '...oxMMMMMMo....',
  '..oeMMMMMMmmo...',
  '...ooMmmmmmoMo..',
  '.....oooooo.oMo.',
  '..............o.',
  '................',
  '................',
];

const BED = [
  '................',
  '................',
  '................',
  '................',
  '.....oooooo.....',
  '...ooRRRRRRoo...',
  '..oRRQQQQQQRRo..',
  '.oRQIIIIIIIIQRo.',
  '.oRQIiiiiiiIQRo.',
  '.oRQIiiiiiiIQRo.',
  '.oRRQIIIIIIQRRo.',
  '.oRRRRRRRRRRRRo.',
  '.oQRRRRRRRRRRQo.',
  '..oQQQQQQQQQQo..',
  '...oooooooooo...',
  '................',
];

const SCRATCHING_POST = [
  '................',
  '................',
  '................',
  '................',
  '....oooooooo....',
  '...oCLLLLLLCo...',
  '...oCCCCCCCCo...',
  '...occccccccoo..',
  '....oooSSoooYo..',
  '......oSso.oYo..',
  '......orro..o...',
  '......oSso..o...',
  '......oSso.oYo..',
  '......orro.oyo..',
  '......oSso..o...',
  '......oSso......',
  '......orro......',
  '......oSso......',
  '......oSso......',
  '......orro......',
  '......oSso......',
  '......oSso......',
  '......orro......',
  '......oSso......',
  '......oSso......',
  '......orro......',
  '..oooooooooooo..',
  '.oWWWWWWWWWWWWo.',
  '.oWWWWWWWWWWWWo.',
  '.owwwwwwwwwwwwo.',
  '.ovvvvvvvvvvvvo.',
  '..oooooooooooo..',
];

const TEASER = [
  '................',
  '...ooooooo......',
  '..oPPPPPPPoo....',
  '.oPooooooPPo....',
  '.oPo.....oPo....',
  '.oo......oPo....',
  'oGo......oPo....',
  'oGfo.....oPo....',
  'ofFfo....oPo....',
  'oFFfo....oPo....',
  'oFFFo....oPo....',
  '.oFFo....oPo....',
  '.oFo.....oPo....',
  '..o......oPo....',
  '.........oPo....',
  '.........oPo....',
  '.........oPo....',
  '.........oPo....',
  '.........oPo....',
  '.........oPo....',
  '.........oPo....',
  '.........oPo....',
  '.........oPo....',
  '.........oPo....',
  '.........oPo....',
  '.........opo....',
  '.......oopppoo..',
  '......oWWWWWWWo.',
  '......oWWWWWWWo.',
  '......owwwwwwwo.',
  '.......ooooooo..',
  '................',
];

const TUNNEL = [
  '................................',
  '................................',
  '................................',
  '....oooooooooooooooooooooooo....',
  '..ooTTTTuTTTTTTuTTTTTTuTTTTToo..',
  '.oqoTTTTuTTTTTTuTTTTTTuTTTTToqo.',
  'oqqqoTTTuTTTTTTuTTTTTTuTTTToqqqo',
  'oqqqoTTTuTTTTTTuTTTTTTuTTTToqqqo',
  'oqqqoTTTuTTTTTTuTTTTTTuTTTToqqqo',
  'oqqqonnnunnnnnnunnnnnnunnnnoqqqo',
  'oqqqonnnunnnnnnunnnnnnunnnnoqqqo',
  '.oqoonnnunnnnnnunnnnnnunnnnooqo.',
  '..oooooooooooooooooooooooooooo..',
  '................................',
  '................................',
  '................................',
];

const CAT_TREE = [
  '................................',
  '................................',
  '................................',
  '................................',
  '.....oooooooooooooooooooooo.....',
  '....oCLLLLLLLLLLLLLLLLLLLLCo....',
  '....oCCCCCCCCCCCCCCCCCCCCCCo....',
  '....oCCCCCCCCCCCCCCCCCCCCCCo....',
  '....occcccccccccccccccccccco....',
  '.....ooooooooSSoooooooooooo.....',
  '............oSso................',
  '............orro................',
  '............oSso................',
  '............oSso................',
  '............orro................',
  '............oSso................',
  '..ooooooooooooSsoooo............',
  '.oCLLLLLLLLLLLLLLLLCo...........',
  '.oCCCCCCCCCCCCCCCCCCo...........',
  '.occcccccccccccccccco...........',
  '..oooooSSooooooooooo..oo........',
  '......oSso...oSso....oYo........',
  '......orro...orro....oyo........',
  '......oSso...oSso.....o.........',
  '......oSso...oSso...............',
  '......orro...orro...............',
  '......oSso...oSso...............',
  '......oSso...oSso...............',
  '......orro...orro...............',
  '......oSso...oSso...............',
  '......oSso...oSso...............',
  '......orro...orro...............',
  '......oSso...oSso...............',
  '......oSso...oSso...............',
  '......orro...orro...............',
  '......oSso...oSso...............',
  '......oSso...oSso...............',
  '......orro...orro...............',
  '..oooooooooooooooooooooooooooo..',
  '.oCLLLLLLLLLLLLLLLLLLLLLLLLLLCo.',
  '.oCCCCCCCCCCCCCCCCCCCCCCCCCCCCo.',
  '.oCCCCCCCCCCCCCCCCCCCCCCCCCCCCo.',
  '.occcccccccccccccccccccccccccco.',
  '.oWWWWWWWWWWWWWWWWWWWWWWWWWWWWo.',
  '.owwwwwwwwwwwwwwwwwwwwwwwwwwwwo.',
  '.ovvvvvvvvvvvvvvvvvvvvvvvvvvvvo.',
  '..oooooooooooooooooooooooooooo..',
  '................................',
];

/**
 * Every toy: one furniture folder with a manifest. footprint and
 * backgroundTiles follow the existing assets (a tall item blocks only its
 * bottom row).
 */
export const TOYS = [
  { id: 'SCRATCHING_POST', name: 'Scratching Post', rows: SCRATCHING_POST, fw: 1, fh: 2, bg: 1 },
  { id: 'CAT_TREE', name: 'Cat Tree', rows: CAT_TREE, fw: 2, fh: 3, bg: 2 },
  { id: 'YARN_BALL', name: 'Ball of Yarn', rows: YARN, fw: 1, fh: 1, bg: 0 },
  { id: 'CARDBOARD_BOX', name: 'Cardboard Box', rows: BOX_ROWS, fw: 1, fh: 1, bg: 0 },
  { id: 'FEATHER_TEASER', name: 'Feather Teaser', rows: TEASER, fw: 1, fh: 2, bg: 1 },
  { id: 'PLAY_TUNNEL', name: 'Play Tunnel', rows: TUNNEL, fw: 2, fh: 1, bg: 0 },
  { id: 'CAT_BED', name: 'Cat Bed', rows: BED, fw: 1, fh: 1, bg: 0 },
  { id: 'TOY_MOUSE', name: 'Toy Mouse', rows: MOUSE, fw: 1, fh: 1, bg: 0 },
];
