import type { RequestKind } from '../petCare/petNeeds.js';
import type { SpriteData } from '../types.js';
import pack from './petCareSprites.json';

/**
 * Pet-care sprite pack, generated by scripts/generate-pet-care-sprites.mjs
 * (edit scripts/petCare/art.mjs, not the JSON). Rows are palette-char strings;
 * '.' is transparent.
 */
type Rows = string[];

const palette: Record<string, string> = pack.palette;

function resolve(rows: Rows): SpriteData {
  return rows.map((row) => [...row].map((ch) => (ch === '.' ? '' : (palette[ch] ?? ''))));
}

const s = pack.sprites;

/** Bowl combo by food level × water level (each 0..3). */
const BOWLS: SpriteData[][] = s.bowl.map((byWater) => byWater.map(resolve));
/** Litter box: clean, used, full. */
const LITTER: SpriteData[] = s.litter.map(resolve);

export const POOP_SPRITE: SpriteData = resolve(s.poop);
export const STINK_FRAMES: SpriteData[] = s.stink.map(resolve);
export const HEART_SPRITE: SpriteData = resolve(s.heart);
export const SPARKLE_FRAMES: SpriteData[] = s.sparkle.map(resolve);
export const HAND_FRAMES: SpriteData[] = s.hand.map(resolve);
export const YARN_FRAMES: SpriteData[] = s.yarn.map(resolve);
export const DISH_SPRITE: SpriteData = resolve(s.dish);

export const REQUEST_BUBBLES: Record<RequestKind, SpriteData> = {
  food: resolve(s.requests.food),
  water: resolve(s.requests.water),
  scratch: resolve(s.requests.scratch),
  play: resolve(s.requests.play),
  litter: resolve(s.requests.litter),
};

export type PetMenuIcon = keyof typeof s.icons;
export const MENU_ICONS: Record<PetMenuIcon, SpriteData> = Object.fromEntries(
  Object.entries(s.icons).map(([k, rows]) => [k, resolve(rows)]),
) as Record<PetMenuIcon, SpriteData>;

/** 0..max → 0..3 fill step; anything above zero shows at least the low step. */
function step(v: number, max: number): number {
  if (v <= 0) return 0;
  return Math.max(1, Math.min(3, Math.ceil((v / max) * 3)));
}

export function bowlSprite(food: number, water: number, max: number): SpriteData {
  return BOWLS[step(food, max)][step(water, max)];
}

export function litterSprite(count: number, capacity: number): SpriteData {
  if (count <= 0) return LITTER[0];
  return count >= capacity ? LITTER[2] : LITTER[1];
}
