import { furnitureKind } from '../layout/furnitureCatalog.js';
import type { RequestKind } from '../petCare/petNeeds.js';
import type { SpriteData } from '../types.js';
import pack from './petCareSprites.json';

/**
 * Pet-care sprite pack, generated by scripts/generate-pet-care-sprites.mjs
 * (edit scripts/petCare/art.mjs, not the JSON). Rows are palette-char strings;
 * '.' is transparent.
 */
type Rows = string[];

const palette: Record<string, string> = pack.palette;

function resolve(rows: Rows): SpriteData {
  return rows.map((row) => [...row].map((ch) => (ch === '.' ? '' : (palette[ch] ?? ''))));
}

const s = pack.sprites;

/** Bowl combo by food level × water level (each 0..3). */
const BOWLS: SpriteData[][] = s.bowl.map((byWater) => byWater.map(resolve));
/** Litter boxes by catalog type: sprites[piles 0..5][sand 0 fresh, 1 used, 2 dirty]. */
const LITTER_BOXES = new Map(
  Object.entries(s.litterBoxes).map(([type, b]) => [
    type,
    {
      stages: b.stages.map((bySand) => bySand.map(resolve)),
      lipTop: b.lipTop,
      hooded: b.hooded,
    },
  ]),
);

export const POOP_SPRITE: SpriteData = resolve(s.poop);
export const STINK_FRAMES: SpriteData[] = s.stink.map(resolve);
export const HEART_SPRITE: SpriteData = resolve(s.heart);
export const SPARKLE_FRAMES: SpriteData[] = s.sparkle.map(resolve);
export const HAND_FRAMES: SpriteData[] = s.hand.map(resolve);
export const YARN_FRAMES: SpriteData[] = s.yarn.map(resolve);
export const DISH_SPRITE: SpriteData = resolve(s.dish);
export const FLY_FRAMES: SpriteData[] = s.fly.map(resolve);
export const SCOOP_FRAMES: SpriteData[] = s.scoop.map(resolve);
export const BAG_FRAMES: SpriteData[] = s.bag.map(resolve);
export const POUR_FRAMES: SpriteData[] = s.pour.map(resolve);

export const REQUEST_BUBBLES: Record<RequestKind, SpriteData> = {
  food: resolve(s.requests.food),
  water: resolve(s.requests.water),
  scratch: resolve(s.requests.scratch),
  play: resolve(s.requests.play),
  litter: resolve(s.requests.litter),
};

export type PetMenuIcon = keyof typeof s.icons;
export const MENU_ICONS: Record<PetMenuIcon, SpriteData> = Object.fromEntries(
  Object.entries(s.icons).map(([k, rows]) => [k, resolve(rows)]),
) as Record<PetMenuIcon, SpriteData>;

/** 0..max → 0..3 fill step; anything above zero shows at least the low step. */
function step(v: number, max: number): number {
  if (v <= 0) return 0;
  return Math.max(1, Math.min(3, Math.ceil((v / max) * 3)));
}

export function bowlSprite(food: number, water: number, max: number): SpriteData {
  return BOWLS[step(food, max)][step(water, max)];
}

/** Catalog types that are litter boxes (one per art variant). */
export const LITTER_BOX_TYPES: readonly string[] = [...LITTER_BOXES.keys()];

/** The hooded box hides a cat inside: only its tail shows at the door. */
export function isHoodedLitterBox(type: string): boolean {
  return LITTER_BOXES.get(furnitureKind(type))?.hooded === true;
}

/** A box's sprite for `piles` (clamped 0..5) on sand stage 0 fresh, 1 used, 2 dirty. */
export function litterBoxSprite(type: string, piles: number, sand: number): SpriteData | undefined {
  const stages = LITTER_BOXES.get(furnitureKind(type))?.stages;
  if (!stages) return undefined;
  const row = stages[Math.max(0, Math.min(stages.length - 1, Math.round(piles)))];
  return row[Math.max(0, Math.min(row.length - 1, sand))];
}

const fronts = new WeakMap<SpriteData, SpriteData>();

/**
 * The front wall of a box sprite (its rows from the variant's lip down), drawn
 * once more in front of a cat on the tile so the cat stands IN the box.
 */
export function litterFrontSprite(type: string, sprite: SpriteData): SpriteData {
  let front = fronts.get(sprite);
  if (!front) {
    const lip = LITTER_BOXES.get(furnitureKind(type))?.lipTop ?? sprite.length;
    front = sprite.map((row, y) => (y < lip ? row.map(() => '') : row));
    fronts.set(sprite, front);
  }
  return front;
}
