/**
 * Sprites for cat social scenes, decoded from cat-social.json (generated by
 * scripts/generate-cat-sprites.mjs via scripts/cats/social.mjs — edit the
 * generator, not the JSON).
 *
 * Every frame is a list of row strings; each character indexes its palette
 * as (charCode - 48). Overlay palette entries 'furA' / 'furB' are filled with
 * the two fighting cats' fur colours.
 */
import { adjustSprite } from '../colorize.js';
import type { Character, Direction, SocialIcon, SpriteData } from '../types.js';
import { Direction as Dir } from '../types.js';
import sheetJson from './cat-social.json';

type DirName = 'down' | 'up' | 'right';
type Frames = string[][];

interface SocialCatJson {
  name: string;
  palette: string[];
  talk: Record<DirName, Frames>;
}

interface SocialSheetJson {
  overlayPalette: string[];
  overlays: Record<string, Frames>;
  cats: SocialCatJson[];
}

const sheet = sheetJson as SocialSheetJson;
const FUR_A = 'furA';
const FUR_B = 'furB';

function decode(rows: string[], palette: string[], fill?: Record<string, string>): SpriteData {
  return rows.map((row) =>
    [...row].map((c) => {
      const v = palette[c.charCodeAt(0) - 48] ?? '';
      return fill?.[v] ?? v;
    }),
  );
}

const flip = (s: SpriteData): SpriteData => s.map((row) => [...row].reverse());

const cache = new Map<string, SpriteData>();
function cached(key: string, make: () => SpriteData): SpriteData {
  let s = cache.get(key);
  if (!s) {
    s = make();
    cache.set(key, s);
  }
  return s;
}

export function getSocialBubbleSprite(icon: SocialIcon): SpriteData {
  return cached(`bubble:${icon}`, () =>
    decode(sheet.overlays[`bubble_${icon}`][0], sheet.overlayPalette),
  );
}

export function getAngerSprite(frame: number): SpriteData {
  const frames = sheet.overlays.anger;
  return cached(`anger:${frame % frames.length}`, () =>
    decode(frames[frame % frames.length], sheet.overlayPalette),
  );
}

export const SOCIAL_CLOUD_FRAMES = sheet.overlays.cloud.length;

/** Dust cloud frame with paws / tails in the two cats' fur colours. */
export function getCloudSprite(frame: number, furA: string, furB: string): SpriteData {
  const f = frame % SOCIAL_CLOUD_FRAMES;
  return cached(`cloud:${f}:${furA}:${furB}`, () =>
    decode(sheet.overlays.cloud[f], sheet.overlayPalette, { [FUR_A]: furA, [FUR_B]: furB }),
  );
}

function dirName(dir: Direction): { name: DirName; mirror: boolean } {
  if (dir === Dir.UP) return { name: 'up', mirror: false };
  if (dir === Dir.RIGHT) return { name: 'right', mirror: false };
  if (dir === Dir.LEFT) return { name: 'right', mirror: true };
  return { name: 'down', mirror: false };
}

/**
 * Talk frame for a cat, or null when the palette has no social art
 * (the renderer then keeps the normal sprite). Repeated palettes beyond the
 * generated breeds get the same hue shift as their regular sprites.
 */
export function getSocialPoseSprite(
  palette: number,
  hueShift: number,
  pose: 'talk',
  dir: Direction,
  frame: number,
): SpriteData | null {
  if (sheet.cats.length === 0) return null;
  const cat = sheet.cats[palette % sheet.cats.length];
  const { name, mirror } = dirName(dir);
  const frames = cat[pose][name];
  const f = frame % frames.length;
  return cached(`${palette}:${hueShift}:${pose}:${dir}:${f}`, () => {
    let s = decode(frames[f], cat.palette);
    if (mirror) s = flip(s);
    if (hueShift !== 0) s = adjustSprite(s, { h: hueShift, s: 0, b: 0, c: 0 });
    return s;
  });
}

/**
 * Talk frame of a cat: the frames of its custom coat (generated at
 * runtime, see appearanceSprites.ts), else the breed art of its palette.
 */
export function socialPoseOf(
  ch: Pick<Character, 'palette' | 'hueShift' | 'dir' | 'customSprites'>,
  pose: 'talk',
  frame: number,
): SpriteData | null {
  const custom = ch.customSprites?.social?.[pose][ch.dir];
  if (custom?.length) return custom[frame % custom.length];
  return getSocialPoseSprite(ch.palette, ch.hueShift, pose, ch.dir, frame);
}

/** A cat's main fur colour (fight cloud paws, house peek): its custom coat, else its breed. */
export function furColorOf(ch: Pick<Character, 'palette' | 'hueShift' | 'customSprites'>): string {
  const talk = ch.customSprites?.social?.talk[Dir.DOWN][0];
  return talk ? mainFur(talk) : getFurColor(ch.palette, ch.hueShift);
}

/**
 * The cat's main fur colour: the most common pixel of its front talk frame,
 * ignoring the outline (the first opaque pixel, top of an ear).
 */
export function getFurColor(palette: number, hueShift: number): string {
  const sprite = getSocialPoseSprite(palette, hueShift, 'talk', Dir.DOWN, 0);
  return sprite ? mainFur(sprite) : '';
}

/** Most common pixel of a cat frame, ignoring the outline (cached per frame). */
const furCache = new WeakMap<SpriteData, string>();
function mainFur(sprite: SpriteData): string {
  const hit = furCache.get(sprite);
  if (hit !== undefined) return hit;
  const counts = new Map<string, number>();
  let outline: string | null = null;
  for (const row of sprite)
    for (const px of row) {
      if (!px) continue;
      outline ??= px;
      if (px !== outline) counts.set(px, (counts.get(px) ?? 0) + 1);
    }
  let best = outline ?? '';
  let max = 0;
  for (const [px, n] of counts)
    if (n > max) {
      best = px;
      max = n;
    }
  furCache.set(sprite, best);
  return best;
}
